language: node_js
node_js: stable
os: linux
sudo: required

install:
  - npm run bootstrap
script:
  - npm run build
  - npm run test:ci
  - npm run e2e

git:
  depth: 5

cache:
  directories:
    - node_modules
